### ISSUE TITLE
GEV tutorial is broken

### ISSUE THREAD

**Issue by jobrachem** [liesel-devs/liesel#106]
The tutorial using the GEV is broken. The IWLS sampler has a 100% rate of nan acceptance probability.

https://docs.liesel-project.org/en/latest/tutorials/md/03-gev.html

<img width="699" alt="image" src="https://github.com/liesel-devs/liesel/assets/37882800/21798f16-7635-4ffc-8bad-a547e15d01ea">

<img width="705" alt="image" src="https://github.com/liesel-devs/liesel/assets/37882800/7c3c6fcc-541a-4396-a8c5-14b877d1405b">

The last version in which it looked kind-of alright was v2.4:

https://docs.liesel-project.org/en/v0.2.4/tutorials/md/03-gev.html

<img width="817" alt="image" src="https://github.com/liesel-devs/liesel/assets/37882800/bfb6a3fe-227f-4c26-832d-8011e59bc31b">

<img width="710" alt="image" src="https://github.com/liesel-devs/liesel/assets/37882800/c63ddcb7-39e3-4669-8d8d-1da5f9d9edcb">

At the moment I don't know what causes this.

**Comment by wiep** [comment]
problem shows up in the docs since liesel 0.2.5.

**Comment by wiep** [comment]
One chain is stuck in the rendered tutorial.

**Comment by jobrachem** [comment]
In the most recent version, there's still a stuck chain, although it seems to be a different one than in the "stable" version.


https://docs.liesel-project.org/en/latest/tutorials/md/03-gev.html

![Image](https://github.com/liesel-devs/liesel/assets/37882800/a05d387f-20d9-4a1f-8e69-a6ee875bfa0b)

**Comment by jobrachem** [comment]
Hooray, it's fixed now! :-) 



![Image](https://github.com/liesel-devs/liesel/assets/37882800/fd798116-e75a-4eca-972b-697493337f1f)
