### ISSUE TITLE
NUTS kernel in "comparing samplers" tutorial looks very bad

### ISSUE THREAD

**Issue by jobrachem** [liesel-devs/liesel#107]
Link: https://docs.liesel-project.org/en/latest/tutorials/md/04-mcycle.html

Looking at these trace plots, something must be wrong here:

<img width="807" alt="image" src="https://github.com/liesel-devs/liesel/assets/37882800/3b8e18af-26e6-4b9b-9981-ca2e259547c3">

I have not had the time to have a closer look yet.

**Comment by wiep** [comment]
Maybe something went wrong with the update to blackjax 1.0.0.
