### ISSUE TITLE
EngineBuilder: What's the difference between the "seed" init argument and the seed set by "set_engine_seed"?

### ISSUE THREAD

**Issue by jobrachem** [liesel-devs/liesel#111]
This is not clear to me from the documentation. @wiep or @GianmarcoCallegher, could you clear this up? Probably what's needed is predominantly a clarification in the docs.

**Comment by GianmarcoCallegher** [comment]
Looks like there is no difference. Also, `set_engine_seed` is not even used in the tests. Maybe an old version of the constructor didn't take the seed and that method was used for setting it?

**Comment by wiep** [comment]
If i recall correctly: the seed in the builder is used for the things that happen in the builder and required prng state. moreover, it is initially split to have a value for the engine seed. However, the user can overwrite the engine seed using `set_engine_seed`. The engine seed is used for the PRNG in the sampling process.

```
seed --+--> use in builder
       |--> use in engine / sampling    <-- can be overwritten with set_engine_seed.
```

**Comment by jobrachem** [comment]
Thanks for clearing that up! Will be useful for

-  #118
