### ISSUE TITLE
Make Gibbs sampler setup more convenient

### ISSUE THREAD

**Issue by jobrachem** [liesel-devs/liesel#220]
Assume I have a variable `a = lsl.Var.new_param(1.0, name="a")`. If I want to construct a Gibbs sampler for this variable, I need to define a transition function that acts on the model state and returns a position dictionary. The key of the correct object in the model state will be `"a_value"`, or, even worse `"a_var_value"`. From a user perspective, this is inconvenient and unexpected. The current solution is to use a `lsl.Group`, but a more general solution would be nice I think.

**Comment by wiep** [comment]
I think, we usually avoid working directly on the model state but use a model interface, i.e., use the methods `interface.extract_position` and `interface.update_state`.

**Comment by jobrachem** [comment]
Sounds reasonable, thanks!
