### ISSUE TITLE
Rename helper functions: Param -> param

### ISSUE THREAD

**Issue by jobrachem** [liesel-devs/liesel#53]
We have some helper functions that are capitalized at the moment. Users might expect them to be classes because of Python's naming conventions. This issue is about renaming them to avoid this confusion.

- [ ] Param -> param
- [ ] Obs -> obs
- [ ] Anything else?

**Comment by wiep** [comment]
functions should be named like imperative verbs if possible. However, adding a prefix like `make_` or `create_` does not really add much. There are also example like `type` and `length` un the stdlib which do not follow this recommendation.

**Comment by jobrachem** [comment]
To be honest, I think my actual preferred solution would be to just make these helper functions proper classes. I repeatedly find myself trying to subclass them, because it just feels like the natural thing to do for me, when I want to create some reusable specialized node.

**Comment by jobrachem** [comment]
The discussion converged to the small letter versions `obs` and `param`.
