### ISSUE TITLE
The name of `Model.groups` indicates a field/property

### ISSUE THREAD

**Issue by wiep** [liesel-devs/liesel#58]
I feel the name of `Model.groups` is obscure. The word indicates to me a property or field similar to `vars` or `nodes`. It is, however , a method. I think we should either choose an imperative like `get_groups` or make it a property.

**Comment by hriebl** [comment]
Old discussions:

- https://github.com/liesel-devs/liesel-nextgen/pull/16#issuecomment-1301838570
- https://github.com/liesel-devs/liesel-nextgen/pull/42#issuecomment-1319819271
