### ISSUE TITLE
Remove pinned dependency on pydata-sphinx-theme

### ISSUE THREAD

**Issue by jobrachem** [liesel-devs/liesel#61]
I pinned down the dependency in #60.

Once 

- [x] https://github.com/executablebooks/sphinx-book-theme/issues/711

is fixed, we can remove the pinned dependency.

**Comment by hriebl** [comment]
Apparently the upstream issue is fixed, so we should be able to unpin the dependency.

**Comment by jobrachem** [comment]
👍 ✅
