### ISSUE TITLE
MVNDegenerate test fails with TFP 0.20.1

### ISSUE THREAD

**Issue by hriebl** [liesel-devs/liesel#67]
Here's the error message:

```
FAILED tests/distributions/test_mvn_degen.py::TestMVNDegenerateAgainstTensorFlow::test_multiple_samples - ValueError: Incompatible shapes for broadcasting: (1, 3, 5, 1) and requested shape (2, 2, 5, 1)
```

See also our [CI log](https://github.com/liesel-devs/liesel/actions/runs/5221892365/jobs/9426719770). Downgrading to TFP 0.19 solves the issue, but we should probably investigate more thoroughly what's going on...

**Comment by jobrachem** [comment]
Interesting. The code below is pasted from the test that resulted in the error. It expects a TypeError, but we get a ValueError. Maybe they just updated the error message. Interestingly, the code also already contains a comment about varying error messages.

```python
# The tfd version apparently does not always raise the same error if shapes
# are not compatible for broadcasting. Here, it raises a TypeError.
# Sample shape: (1, 3, 5)
# Batch shape: (2, 2)
sample = jnp.array([[beta, beta, beta]])
with pytest.raises(TypeError):
    mvn.log_prob(sample)
```
